# Generated by Django 2.2.7 on 2019-11-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
